apiVersion: v1
kind: Service
metadata:
  name: mailbox-svc
  namespace: web
  labels:
    app: mailbox
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30003
  selector:
    app: mailbox
